import type { ReactNode } from "react";

export function Panel({
  title,
  eyebrow,
  children,
  className = "",
}: {
  title?: string;
  eyebrow?: string;
  children: ReactNode;
  className?: string;
}) {
  return (
    <div className={`border border-[var(--color-line)] bg-[var(--color-panel)] rounded-sm ${className}`}>
      {(title || eyebrow) && (
        <div className="px-5 pt-4 pb-3 border-b border-[var(--color-line)]">
          {eyebrow && (
            <div className="font-mono text-[10px] uppercase tracking-widest text-[var(--color-text-faint)]">
              {eyebrow}
            </div>
          )}
          {title && <div className="font-display text-lg mt-0.5">{title}</div>}
        </div>
      )}
      <div className="p-5">{children}</div>
    </div>
  );
}

export function DemoBadge() {
  return (
    <span className="inline-flex items-center gap-1.5 font-mono text-[10px] uppercase tracking-widest text-[var(--color-amber)] border border-[var(--color-amber-dim)] rounded-sm px-2 py-1">
      <span className="w-1.5 h-1.5 rounded-full bg-[var(--color-amber)]" />
      Demo data — not generated by a research experiment
    </span>
  );
}

export function StatCard({
  label,
  value,
  sub,
}: {
  label: string;
  value: string;
  sub?: string;
}) {
  return (
    <div className="border border-[var(--color-line)] bg-[var(--color-panel)] rounded-sm p-4">
      <div className="font-mono text-[10px] uppercase tracking-widest text-[var(--color-text-faint)]">
        {label}
      </div>
      <div className="font-display text-3xl mt-2 text-[var(--color-text)]">{value}</div>
      {sub && <div className="font-mono text-[11px] text-[var(--color-text-dim)] mt-1">{sub}</div>}
    </div>
  );
}
