"""
Demo Mode data generator.

Produces a clearly-labeled synthetic dataset so the dashboard is
useful even with no Ollama installation. Every record this module
creates has is_demo=1 in the database, and the API/frontend must
display the "DEMO DATA -- NOT GENERATED BY A RESEARCH EXPERIMENT"
label wherever it appears. This module never claims its numbers are
real research results.
"""

import random
import uuid

from app.database import get_conn, now_iso, dumps
from app.services.question_bank import get_question_bank

CONDITIONS = ["memory", "personality", "values", "goals", "model", "progressive"]
TRANSFORMATIONS = list(range(0, 101, 10))
DEMO_MODEL_NAME = "demo-model"


def _synthetic_curve(condition: str, pct: int, rng: random.Random) -> float:
    """A plausible-looking but entirely synthetic decline curve per condition."""
    base_slope = {
        "memory": 0.55,
        "personality": 0.70,
        "values": 0.35,
        "goals": 0.45,
        "model": 0.85,
        "progressive": 0.60,
    }.get(condition, 0.5)

    decline = pct * base_slope
    # Inject one artificial "boundary" around 50-70% for model and progressive
    if condition in ("model", "progressive") and pct >= 60:
        decline += 15
    noise = rng.uniform(-4, 4)
    score = max(0.0, min(100.0, 100 - decline + noise))
    return round(score, 1)


def generate_demo_dataset(seed: int = 7):
    rng = random.Random(seed)
    questions = get_question_bank()

    with get_conn() as conn:
        cur = conn.cursor()
        cur.execute("DELETE FROM scores WHERE experiment_id IN (SELECT id FROM experiments WHERE is_demo=1)")
        cur.execute("DELETE FROM responses WHERE run_id IN (SELECT id FROM runs WHERE experiment_id IN (SELECT id FROM experiments WHERE is_demo=1))")
        cur.execute("DELETE FROM runs WHERE experiment_id IN (SELECT id FROM experiments WHERE is_demo=1)")
        cur.execute("DELETE FROM experiments WHERE is_demo=1")

        for condition in CONDITIONS:
            for pct in TRANSFORMATIONS:
                exp_id = f"demo_{condition}_{pct}"
                cur.execute(
                    """INSERT INTO experiments
                    (id, baseline, variant, condition, transformation_percentage, model,
                     blind_condition, trial_count, random_seed, prompt_version, is_demo,
                     created_at, status)
                    VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)""",
                    (exp_id, "EIDOLON-0", f"EIDOLON-{pct}", condition, pct, DEMO_MODEL_NAME,
                     0, 5, seed, "identity_v1", 1, now_iso(), "complete"),
                )

                for trial in range(5):
                    for q in questions:
                        run_id = str(uuid.uuid4())
                        cur.execute(
                            """INSERT INTO runs
                            (id, experiment_id, trial_index, question_id, question_text, perspective, created_at)
                            VALUES (?,?,?,?,?,?,?)""",
                            (run_id, exp_id, trial, q["id"], q["text"], q["perspective"], now_iso()),
                        )

                        score = _synthetic_curve(condition, pct, rng)
                        confidence = round(max(0.3, min(0.99, rng.uniform(0.55, 0.95))), 2)
                        same_entity = score >= 50
                        primary_prop = rng.choice(["memory", "personality", "values", "goals", "model"])
                        reason = "Synthetic demo reasoning generated for illustration purposes only."

                        response_id = str(uuid.uuid4())
                        parsed = {
                            "same_entity": same_entity,
                            "identity_score": score,
                            "confidence": confidence,
                            "primary_identity_property": primary_prop,
                            "reason": reason,
                        }
                        cur.execute(
                            """INSERT INTO responses
                            (id, run_id, raw_response, parsed_json, parse_failed, latency_ms, created_at)
                            VALUES (?,?,?,?,?,?,?)""",
                            (response_id, run_id, "[DEMO DATA -- synthetic]", dumps(parsed), 0,
                             rng.randint(200, 900), now_iso()),
                        )

                        score_id = str(uuid.uuid4())
                        cur.execute(
                            """INSERT INTO scores
                            (id, experiment_id, run_id, same_entity, identity_score, confidence,
                             primary_identity_property, reason)
                            VALUES (?,?,?,?,?,?,?,?)""",
                            (score_id, exp_id, run_id, int(same_entity), score, confidence,
                             primary_prop, reason),
                        )
        conn.commit()
